services:
  - type: web
    name: agridoc-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main_app:app
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: 1
